#include QMK_KEYBOARD_H
#include "keymap.h"
#include "g/keymap_combo.h"

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[BASE] = LAYOUT(
    KC_Q, KC_W, KC_F, KC_P, KC_B, KC_J, KC_L, KC_U, KC_Y, KC_QUOT,
    KC_A, KC_R, KC_S, KC_T, KC_G, KC_M, HM_N, KC_E, KC_I, KC_O,
    MT(MOD_LGUI,KC_Z), KC_X, KC_C, KC_D, KC_V, KC_K, KC_H, MT(MOD_LALT | MOD_RALT,KC_COMM), MT(MOD_LCTL | MOD_RCTL,KC_DOT), KC_GRV,
    LTHUMB_OUT, LTHUMB_IN, RTHUMB_IN, RTHUMB_OUT
  ),
	[NUM] = LAYOUT(
    KC_ESC, KC_P7, KC_P8, KC_P9, KC_VOLU, KC_MNXT, KC_MPRV, KC_MPLY, KC_TRNS, KC_BSPC,
    KC_TAB, KC_P4, KC_P5, KC_P6, KC_VOLD, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, MT(MOD_LGUI, KC_TRNS),
    KC_P0, KC_P1, KC_P2, KC_P3, KC_MUTE, LCA(KC_LEFT), LCA(KC_DOWN), LCA(KC_UP), LCA(KC_RGHT), LCA(KC_ENT),
    KC_TRNS, KC_LSFT, KC_TRNS, KC_TRNS
  ),
	[NAV] = LAYOUT(
    KC_GRV, KC_LPRN, KC_RPRN, KC_LCBR, KC_RCBR, KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC,
    KC_SLSH, KC_LBRC, KC_RBRC, KC_LT, KC_GT, KC_CIRC, KC_AMPR, KC_ASTR, KC_DQUO, KC_PLUS,
    KC_BSLS, KC_PIPE, KC_COLN, KC_SCLN, KC_UNDS, KC_MINS, KC_EQL, KC_QUES, KC_QUOT, KC_TRNS,
    KC_TRNS, KC_LSFT, KC_TRNS, KC_TRNS
  ),
	[FN1] = LAYOUT(
    KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10,
    KC_TRNS, KC_TRNS, KC_KANA, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
  )
};

// TODO
// Get a home row modifiker for command to work.  So far nothing is working.
